/**
 * @namespace: src/commands/utility/rank.js
  * @type: Command
   * @copyright © 2026 Aryandita Praftian
    * @assistant Naura Hoshino
     * @version 1.0.0
      * @description Menampilkan kartu profil level pengguna yang tersinkronisasi per-server.
       */

       const { SlashCommandBuilder, EmbedBuilder, AttachmentBuilder } = require('discord.js');
       const { CanvasUtils } = require('../../utils/Canvas'); 
       const UserLeveling = require('../../models/UserLeveling'); // MENGGUNAKAN MODEL BARU
       const { getNextLevelXp } = require('../../utils/leveling'); // MENGGUNAKAN FUNGSI BARU
       const ui = require('../../config/ui');
       const { Op } = require('sequelize'); // Diperlukan untuk perhitungan peringkat

       module.exports = {
            data: new SlashCommandBuilder()
                    .setName('rank')
                            .setDescription('🌟 Lihat Kartu Profil Eksklusif dinamis kamu di server ini!')
                                    .addUserOption(option => 
                                                option.setName('target')
                                                                .setDescription('Lihat profil milik orang lain')
                                                                                .setRequired(false)
                                                                                        ),
                                                                                            aliases: ['profile', 'level', 'xp'], // Dukungan Hybrid Command (n!rank, n!profile)

                                                                                                async execute(interaction) {
                                                                                                            // Deteksi apakah ini dari Slash Command atau Prefix Command (Mock Interaction)
                                                                                                                    const isSlash = typeof interaction.deferReply === 'function';
                                                                                                                            if (isSlash) await interaction.deferReply();

                                                                                                                                    // Ambil target user (mendukung Slash Command & Prefix Mention)
                                                                                                                                            const targetUser = (interaction.options && typeof interaction.options.getUser === 'function') 
                                                                                                                                                        ? interaction.options.getUser('target') || interaction.user 
                                                                                                                                                                    : interaction.user;

                                                                                                                                                                            const guildId = interaction.guild.id;

                                                                                                                                                                                    // ==========================================
                                                                                                                                                                                            // 💾 1. PENGAMBILAN DATA NYATA DARI DATABASE (PER SERVER)
                                                                                                                                                                                                    // ==========================================
                                                                                                                                                                                                            let userData;
                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                    userData = await UserLeveling.findOne({ 
                                                                                                                                                                                                                                                        where: { userId: targetUser.id, guildId: guildId } 
                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                    console.error('\x1b[31m[RANK ERROR]\x1b[0m Gagal mengambil data user:', error);
                                                                                                                                                                                                                                                const errEmbed = new EmbedBuilder().setColor('#FF0000').setDescription('❌ Terjadi kesalahan saat mengakses database MySQL.');
                                                                                                                                                                                                                                                            return isSlash ? interaction.editReply({ embeds: [errEmbed] }) : interaction.reply({ embeds: [errEmbed] });
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    
                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                    // 🛡️ 2. NULL GUARD (PENANGANAN DATA KOSONG)
                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                    // Jika user belum pernah chat, berikan nilai default
                                                                                                                                                                                                                                                            const currentLevel = userData ? userData.level : 1;
                                                                                                                                                                                                                                                                    const currentXp = userData ? userData.xp : 0;
                                                                                                                                                                                                                                                                            const targetXp = getNextLevelXp(currentLevel);
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                    // ==========================================
                                                                                                                                                                                                                                                                                            // 🏆 3. MENGHITUNG PERINGKAT LOKAL (SERVER RANK)
                                                                                                                                                                                                                                                                                                    // ==========================================
                                                                                                                                                                                                                                                                                                            let localRank = 'N/A';
                                                                                                                                                                                                                                                                                                                    let roleBadge = '✧ Pendatang Baru';
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                            if (userData) {
                                                                                                                                                                                                                                                                                                                                            // Hitung jumlah user di server ini yang XP-nya lebih besar dari targetUser
                                                                                                                                                                                                                                                                                                                                                        const higherUsers = await UserLeveling.count({
                                                                                                                                                                                                                                                                                                                                                                            where: {
                                                                                                                                                                                                                                                                                                                                                                                                    guildId: guildId,
                                                                                                                                                                                                                                                                                                                                                                                                                        xp: { [Op.gt]: currentXp }
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                    localRank = `#${higherUsers + 1}`;
                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                    // Kalkulasi Badge berdasarkan Level
                                                                                                                                                                                                                                                                                                                                            if (currentLevel >= 100) roleBadge = '✦ Legenda Abadi ✦';
                                                                                                                                                                                                                                                                                                                                                    else if (currentLevel >= 50) roleBadge = '✧ Pahlawan Senior';
                                                                                                                                                                                                                                                                                                                                                            else if (currentLevel >= 20) roleBadge = '✧ Petualang Tangguh';
                                                                                                                                                                                                                                                                                                                                                                    else if (currentLevel >= 10) roleBadge = '✧ Pengembara Berbakat';

                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                    // 🖼️ 4. GENERATE GAMBAR CANVAS SECARA OTOMATIS
                                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                    let imageBuffer;
                                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                                            // Panggil fungsi CanvasUtils Anda. (Pastikan fungsi ini sudah Anda buat di Canvas.js)
                                                                                                                                                                                                                                                                                                                                                                                                                                        const canvas = await CanvasUtils.generateRankCard(
                                                                                                                                                                                                                                                                                                                                                                                                                                                            targetUser, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentLevel, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            currentXp, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            targetXp, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            localRank, // Menggantikan globalRank lama
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            roleBadge
                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Dukungan enkripsi buffer untuk @napi-rs/canvas agar tidak error "ReqResourceType"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (canvas && typeof canvas.encodeSync === 'function') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                imageBuffer = canvas.encodeSync('png');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (canvas && typeof canvas.toBuffer === 'function') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                imageBuffer = canvas.toBuffer('image/png');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                imageBuffer = canvas;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            } catch (error) {
                                                                                                                                                                                                                                                                                                                                                                                                                            console.error('\x1b[31m[RANK CANVAS ERROR]\x1b[0m Gagal merender kartu:', error);
                                                                                                                                                                                                                                                                                                                                                                                                                                        const errEmbed = new EmbedBuilder().setColor('#FF0000').setDescription('❌ Terjadi kesalahan saat merender grafis kartu profil.');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    return isSlash ? interaction.editReply({ embeds: [errEmbed] }) : interaction.reply({ embeds: [errEmbed] });
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                    const attachment = new AttachmentBuilder(imageBuffer, { name: 'prestige-rank.png' });
                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                    // 🖥️ 5. MERAKIT EMBED UI PREMIUM
                                                                                                                                                                                                                                                                                                                                                                                                                                            // ==========================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                    const rankEmbed = new EmbedBuilder()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setColor(currentLevel >= 50 ? '#FFD700' : (ui.getColor ? ui.getColor('primary') : '#00FFFF'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setAuthor({ name: `✦  𝐏 𝐑 𝐄 𝐒 𝐓 𝐈 𝐆 𝐄   𝐏 𝐑 𝐎 𝐅 𝐈 𝐋 𝐄  ✦`, iconURL: interaction.client.user.displayAvatarURL() })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setImage('attachment://prestige-rank.png') 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .addFields(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { name: '📜 Statistik Perjalanan', value: `\`Status: Tersinkronisasi dengan ${interaction.guild.name}\``, inline: false }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .setFooter({ text: 'Naura Ultimate System • Divisi Registrasi', iconURL: interaction.client.user.displayAvatarURL() })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setTimestamp();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Mengirim Balasan Akhir
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (isSlash) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.editReply({ embeds: [rankEmbed], files: [attachment] });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.reply({ embeds: [rankEmbed], files: [attachment] })}}}